version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    insecure-external-code-execution: deny
    labels: ["dependencies"]
    commit-message:
      prefix: "deps"
      include: "scope"
    assignees:
      - "takumi0213"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["ci", "dependencies"]
    commit-message:
      prefix: "ci-deps"
      include: "scope"
    assignees:
      - "takumi0213"
    open-pull-requests-limit: 10
